### ISSUE TITLE
No binding for backspace

### ISSUE THREAD

**Issue by zikes** [PolymerElements/iron-a11y-keys-behavior#10]
There is currently no way to bind to backspace.

**Comment by stevehansen** [comment]
Took me some time to figure out that I couldn't use "insert" because it wasn't in the list.

I was using http://www.openjs.com/scripts/events/keyboard_shortcuts/ before and this one has a lot more keys predefined.

Or maybe make it possible to use any hex code?

**Comment by cdata** [comment]
I'm going to close this as a duplicate of #12 .
