### ISSUE TITLE
Capturing up/down arrow keys does not prevent the page from scrolling up/down with arrow keys

### ISSUE THREAD

**Issue by manustays** [PolymerElements/iron-a11y-keys-behavior#13]
Hi,

I am handling up/down arrow keys to change focus on my list items. It keys are being captured properly but the page also scrolls up/down. The event bleeds up to the scrollable container and scrolls it.

I tried event.preventDefault(), event.stopPropagation() & event.stopImmediatePropagation() but the issue is not resolved.

P.S.: I'm using shady-dom.

Kindly help!

**Comment by cdata** [comment]
Hi, you need to use `event.detail.keyboardEvent.preventDefault()` to stop the scrolling right now. However, it would be good for us to add this described behavior as a feature.

**Comment by valdrinkoshi** [comment]
Hi @manustays, how are you capturing the up/down arrow keys events? Do they have the event.detail.keyboardEvent defined?

**Comment by valdrinkoshi** [comment]
@manustays, with v1.0.8 you'll be able to prevent the default behavior when calling event.preventDefault()
```javascript
document.addEventListener('keydown', function(event) {
    if (isDownArrow(event) || isUpArrow(event)) {
        // avoid scrolling
        event.preventDefault();
    }
});

**Comment by inkubux** [comment]
I found a way to make it work without attaching an event listener to the window.

In your call back you can do:

event.detail.keyboardEvent.preventDefault();

and it will stop the browser default behaviour with your event.
