### ISSUE TITLE
Normalize key code in event.detail

### ISSUE THREAD

**Issue by shashi** [PolymerElements/iron-a11y-keys-behavior#14]
In core-a11y-keys the keyboard event was passed through [`keyboardEventToKey`](https://github.com/Polymer/core-a11y-keys/blob/master/core-a11y-keys.html#L236) function which was very helpful because one didn't have to memorize or look up key codes. event.detail contained exactly the amount of information required. Can we have it back? (can I make a Pull-request or is there a reason this was removed?)

**Comment by cdata** [comment]
Can you specify which information is missing?

**Comment by shashi** [comment]
Hello @cdata sorry for the late response. What I did was:

I added this to the prototype, and then call it from my app under the event handler for `"keys-pressed"` event.
```js
      keyboardEventToKey: function (event) {
        return {
          shift: event.shiftKey,
          ctrl: event.ctrlKey,
          meta: event.metaKey,
          alt: event.altKey,
          key: normalizedKeyForEvent(event)
        };
      },
```

Notice that `normalizedKeyForEvent` is only inside the scope of core-a11y-keys and so adding this to the prototype was necessary.

**Comment by valdrinkoshi** [comment]
Update: this information is already available in `event.detail`, in fact you can access to [`keyCombo` properties](https://github.com/PolymerElements/iron-a11y-keys-behavior/blob/master/iron-a11y-keys-behavior.html#L190), e.g. `event.detail.combo, event.detail.key, event.detail.hasModifiers` etc..

@shashi is your request to add a public method `keyboardEventToKey` added to `iron-a11y-keys-behavior`?

**Comment by valdrinkoshi** [comment]
Closing as pending response for 22 days & not actionable
