### ISSUE TITLE
Setting keyEventTarget on element prototype is overwritten.

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/iron-a11y-keys-behavior#19]
For an element that uses this behavior, setting `keyEventTarget` on the element's prototype gets overwritten by the behavior to `this` (the element). 

    keyEventTarget: document.body

My workaround was to set this in `ready`:

```
ready: function() {
  this.keyEventTarget = document.body;
}

**Comment by cdata** [comment]
`keyEventTarget` is a property and should be overwritten in the `properties` block, e.g.

```javascript
properties: {
  keyEventTarget: {
    type: Object,
    value: function() {
      return document.body;
    }
  }
}
```

If I am mis-understanding the issue being reported, please feel free to re-open!
