### ISSUE TITLE
In Chrome M47 (maybe M48) onwards, some key combos don't work

### ISSUE THREAD

**Issue by notwaldorf** [PolymerElements/iron-a11y-keys-behavior#28]
In the demo, `alt+a` no longer works, and adding `shift+tab` doesn't work anymore either (it works in my old M46 Chrome, but not in my Canary).

**Comment by notwaldorf** [comment]
cc @cdata

**Comment by pdgago** [comment]
this could be related to this issue: I'm using chrome (47, 48, 49) under linux and i can't get the special keys of the demo working. I checked and for example the keyIdentifier of the key (+) is the same as the key 'k'. This doesn't happens in firefox. The keyCodes are correct so I can fix the problem switching the order of keyCode and keyIdentifier transformations in the normalizedKeyForEvent function, and then adding the 
o the KEY_CODE table.
