### ISSUE TITLE
'esc' not matched for escape key in Chrome Canary, breaking menus

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/iron-a11y-keys-behavior#38]
[An update to Chrome's treatment of KeyboardEvent](https://codereview.chromium.org/1849473002) (see [intent to ship](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/KhRce4bmnb0)) has broken iron-a11y-keys-behavior's matching logic for the Escape key. This is preventing, for example, [Escape from closing paper-dropdown-menu](https://elements.polymer-project.org/elements/paper-menu-button?view=demo:demo/index.html&active=paper-menu-button) because [iron-menu-behavior treats the key as if it were supposed to be the first character of a menu item](https://github.com/PolymerElements/iron-menu-behavior/blob/master/iron-menu-behavior.html#L305).

This is [affecting Chrome's new Material Design Downloads page](https://bugs.chromium.org/p/chromium/issues/detail?id=599373) as a beta-blocking issue.

A [fix has been proposed](https://codereview.chromium.org/1851573003) (not formatted a patch for this repo though).

Open questions:

1. Do any other keys not work?
2. Is the proposed fix compatible with other browsers?

**Comment by mgiuffrida** [comment]
FTR, this also prevents Escape from closing dialogs.

**Comment by valdrinkoshi** [comment]
Closing, got fixed in https://github.com/PolymerElements/iron-a11y-keys-behavior/pull/39 & released in `v1.1.2`
