### ISSUE TITLE
Autofill causing exceptions

### ISSUE THREAD

**Issue by sandeshdamkondwar** [PolymerElements/iron-a11y-keys-behavior#44]
### Description
Polymer paper-input and any other field with autocomplete causing exceptions when data filled using autocomplete

Had pull request #43  for this before, and for some unknown reason that bug got vanished in the middle. Now it came back again.

### Expected outcome
without exceptions

### Actual outcome
Exception
(Uncaught TypeError: Cannot read property 'key' of undefined)

### Live Demo
http://sandy.co.in/polymer-demos/dest/

### Steps to reproduce

1. Put a `paper-input` element in the page with attribute label="name" & autocomplete="name".
2. Open the page in a web browser.
3. type something and select any autofill option.
4. check the console

### Browsers Affected
- [x] Chrome (Version 53.0.2756.0 dev (64-bit))
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

Platform: OSx El Capitan

**Comment by valdrinkoshi** [comment]
Confirmed, bug present in chrome dev (v 53.0.2756.0).

**Comment by valdrinkoshi** [comment]
Fixed in PR #43 and released in `v1.1.3`
