### ISSUE TITLE
'KeyboardEvent.keyIdentifier' is deprecated warning in Chrome

### ISSUE THREAD

**Issue by web-padawan** [PolymerElements/iron-a11y-keys-behavior#53]
### Description
```
'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.
```

This warning is caused by line 182:
```js
transformKeyIdentifier(keyEvent.keyIdentifier) ||
```
Seems that this should be removed.

**Comment by web-padawan** [comment]
I'm going to send a PR to fix that warning. 
Shouldn't we get rid of the `keyIdentifier` at all?
/cc @valdrinkoshi

**Comment by valdrinkoshi** [comment]
I'm afraid it would be a breaking change as other browsers don't support `key` yet, and the other options (keyCode, charCode) are no better than keyIdentifier...

**Comment by samccone** [comment]
@valdrinkoshi thoughts on falling back to key Identifier if key is not supported?

**Comment by valdrinkoshi** [comment]
@samccone that's already happening, see https://github.com/PolymerElements/iron-a11y-keys-behavior/blob/master/iron-a11y-keys-behavior.html#L178
> Fall back from .key, to .keyIdentifier, to .keyCode, and then to .detail.key to support artificial keyboard events

**Comment by samccone** [comment]
correct, but switching the order of the fallback so that `.keyIdentifier` is lower on the || fall through.
Testing a patch locally now.

**Comment by valdrinkoshi** [comment]
Unfortunately the warning gets displayed anyways if for example you hit "?" (shift + / key in US keyboard). I think that `normalizedKeyForEvent` should be converted to something like:
```javascript
if (keyEvent.key) {
  return transformKey(keyEvent.key, noSpecialChars);
}
if (keyEvent.detail && keyEvent.detail.key) {
  return transformKey(keyEvent.detail.key, noSpecialChars);
}
return transformKeyIdentifier(keyEvent.keyIdentifier) ||
  transformKeyCode(keyEvent.keyCode) || '';
```
I'll take care of that (there are some tests to be fixed)
