### ISSUE TITLE
_unlistenKeyEventListener fails when _boundKeyHandlers is undefined

### ISSUE THREAD

**Issue by maury91** [PolymerElements/iron-a11y-keys-behavior#61]
### Description
When on an ancestor I use Polymer.dom(...).attachChild(), and one of those children has an iron-a11y-keys-behaviour. The method _unlistenKeyEventListener, is called binded to an object without the key _boundKeyHandlers.
The method expects an Array, and calls _boundKeyHandlers.length without checking if the key exists or if is an array, this make the function throws a TypeError.

### Expected outcome

To not throw an error

### Actual outcome

Throws an error

### Stack Trace / Screenshot
![screen shot 2016-12-09 at 13 54 18](https://cloud.githubusercontent.com/assets/4061875/21051325/b20364aa-be17-11e6-8f0e-dfaad00a396f.png)

**Comment by valdrinkoshi** [comment]
Hi @maury91, could you provide a jsbin with the issue? the default value of [`_boundKeyHandlers` is non-null](https://github.com/PolymerElements/iron-a11y-keys-behavior/blob/master/iron-a11y-keys-behavior.html#L295) and the behavior never sets it to another value, so maybe your implementor is setting it to `null`?

**Comment by maury91** [comment]
@valdrinkoshi  I've tried to recreate the conditions for the errors, however in this snippet the error doesn't happen.

https://gist.run/?id=6c408a70f06c3ae45102fbe37a55be56

I put in the snippet everything that I think can cause the problem, even using importHref, but without any result.

The version of the components is the same in both the snippet and the real code.

The error happens when the paper-button is moved to another part of the DOM, and the detach event is fired on each behaviour, it's possible that in the snippet the detach event is not fired, or the property is defined.

I put some debug code to show the value of the property for each paper-button and seems undefined, however, is possible that I can't access that property in the way I'm trying.

// I'm accessing the property only for debug, is not part of the real code

The error I get in the real code is:

```
"TypeError: Cannot read property 'length' of undefined
    at HTMLElement._unlistenKeyEventListeners (http://localhost:8080/bower_components/iron-a11y-keys-behavior/iron-a11y-keys-behavior.html:448:38)
    at HTMLElement.detached (http://localhost:8080/bower_components/iron-a11y-keys-behavior/iron-a11y-keys-behavior.html:333:14)
    at HTMLElement._invokeBehavior (http://localhost:8080/bower_components/polymer/polymer-micro.html:434:4)
    at HTMLElement._doBehavior (http://localhost:8080/bower_components/polymer/polymer-micro.html:427:6)
    at http://localhost:8080/bower_components/polymer/polymer-micro.html:218:6
    at Object.whenReady (http://localhost:8080/bower_components/polymer/polymer-micro.html:101:1)
    at HTMLElement.detachedCallback (http://localhost:8080/bower_components/polymer/polymer-micro.html:216:22)
    at DomApi.(anonymous function) [as appendChild] (http://localhost:8080/bower_components/polymer/polymer-mini.html:1236:26)
    at http://localhost:8080/app/components/cards/novus-card.html:150:27
    at Array.forEach (native)"
```

**Comment by valdrinkoshi** [comment]
@maury91 looks like you're manually doing redistribution of content in the `ready` method of `x-card.html`. That causes useless attach/detach/attach for each children of your x-cards.
You should use the `select` attribute of `<content>` to distribute the content in the correct spots, e.g.
```html
<!-- x-card template -->
<paper-card elevation="0">
   <div id="header">
     <template is="dom-if" if="[[_headerSpinner(headerSpinner,disableLoadingState)]]">
       <paper-spinner id="headerSpinner" active hidden="[[!loading]]"></paper-spinner>
     </template>
     <h1 hidden=[[!heading]]>
       <template is="dom-if" if="[[headerIcon]]">
         <iron-icon class="header-icon" icon="[[headerIcon]]"></iron-icon>
       </template>
       [[heading]]
     </h1>
     <span class="status" hidden=[[!rightText]]>[[rightText]]</span>

     <!-- all headers will go here -->
     <content select="header"></content>

   </div>
   <div>

     <!-- the rest of the content gets distributed here -->
     <content></content>

   </div>
 </paper-card>
```

**Comment by maury91** [comment]
@valdrinkoshi Thank you very much, it worked, and the error stop happening, I will pay more attention to the polymer functions before implementing my ones
