### ISSUE TITLE
this.behaviors property is not available in native 2.0 class-based element

### ISSUE THREAD

**Issue by govis** [PolymerElements/iron-a11y-keys-behavior#69]
### Description

Just tried upgrading  an element to native 2.0 class-based syntax and used <code>Polymer.mixinBehaviors</code> to mix <code>Polymer.PaperInputBehavior</code> this way, which in turn mixes in additional behaviors including <code>Polymer.IronA11yKeysBehavior</code>. 

Unfortunately it seems that <code>Polymer.mixinBehaviors</code>is not setting element's <code>this.behaviors</code> property, which is used by <code>Polymer.IronA11yKeysBehavior</code>, so it fails with an <code>Error TypeError: Cannot read property 'map' of undefined</code> error

https://github.com/PolymerElements/iron-a11y-keys-behavior/blob/2.0-preview/iron-a11y-keys-behavior.html#L374

I am not sure if any other PolymerElements/Behaviors make use of this property and if a change to <code>Polymer.mixinBehaviors</code> is warranted to maintain backward compatibility with hybrid Polymer Elements' behaviors or we shall treat it as a breaking API change.

As it stands right now it appears that this issue will get in the way of moving any element  with a dependency on <code>Polymer.IronA11yKeysBehavior</code> to Polymer 2.0 class-based syntax.

### Expected outcome

No error

### Actual outcome

<code>Error TypeError: Cannot read property 'map' of undefined</code>

https://github.com/PolymerElements/iron-a11y-keys-behavior/blob/2.0-preview/iron-a11y-keys-behavior.html#L374

### Live Demo

http://jsbin.com/gisakayogu/edit?html,console,output

This just shows that this.behaviors is undefined

### Steps to reproduce

1. Run.
2. look for 'undefined' logged to console.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
Closing as it got fixed in Polymer. Thanks for reporting this @govis!
